### ISSUE TITLE
Feedback on Chapter 3

### ISSUE THREAD

**Issue by gkapfham** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-connellyw#10]
Hello @connellyw, here is some feedback for you to consider on Chapter 3!

- Although it is not directly connected to the content that you wrote in Chapter 3, please make sure that you consistently capitalize words in the title of your thesis. This means that "Machine Learning Tool" should also be capitalized in your title. Sounds okay?
- Also, you will need to make sure that you carefully re-format all of the diagrams inside of your senior thesis chapters. Right now the diagrams are not displaying correctly. Please note that you may need to re-write some of the LaTeX source code for the template to get the graphics to render properly. Please see @dluman or me if you have questions about this issue.
- When you include a figure inside of your thesis you also need to make sure that it appears with a figure number and it has a caption.
- Can you give a specific example of calling the API?
- Can you give an example of the output that is returned from the API call?
- Right now, your content in Chapter 3 concludes very abruptly. Can you add some concluding content that draws your discussion together and paves the way for the next chapter?
- Please avoid having pages where there is very little content on the page.
- Overall, this chapter is too short. What other content do you plan to add to it?

**Comment by connellyw** [comment]
added content and fixed formating
