### ISSUE TITLE
Feedback on Chapter 4

### ISSUE THREAD

**Issue by mceccarelli** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-connellyw#11]
Your work in this chapter is fluid and grammatically sound, which helps someone (like me) who isn't as familiar with cryptocurrency or PCA.

I'm happy that you received some of the results that you were looking for, though I do think that more graphics are needed for a complete understanding and a fulfilled chapter.

I also notice that your images are still a bit off, as are my own, in your previous chapters -- though I've addressed this issue in previous remarks.

**Comment by connellyw** [comment]
fixed formating and added graphics
