### ISSUE TITLE
Initial Feedback on Chapter 4

### ISSUE THREAD

**Issue by gkapfham** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-connellyw#12]
Hello @connellyw, here is some preliminary feedback on Chapter 4!

- Please make sure that you provide references for each of the APIs that you are using
- What is your definition of "scalability"? Can you clearly define it and give a reference?
- Make sure that you reference the GitHub repository that provides the working version of your tool.
- Many of the diagrams are really difficult to read. Can you make sure that they are at the same resolution and inside of a figure environment with a caption? You make need to schedule time to chat with @dluman if you have questions about how to use the Markdown-based template!
- Can you please provide a technical diagram and/or an algorithm to illustrate the steps that you followed to conduct the experiments?
- Can you please give an equation for each of your evaluation metrics? For instance, if you are going to report data about "accuracy" you need to define accuracy using an equation. Then, you need to make sure that you give an example of how to calculate accuracy. Finally, you need to make sure that you reference your formal definition of accuracy when you discuss specific graphs.
- For each of the graphs that you include in your thesis, please make sure that you explain the horizontal and vertical axes. You should also offer more details about these results. Finally, are there specific ways in which you can statistically analyze these results?

**Comment by connellyw** [comment]
added more info and diagram, fixed formating
