### ISSUE TITLE
Feedback on Chapters 1 and 2 of Your Senior Thesis

### ISSUE THREAD

**Issue by gkapfham** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-connellyw#8]
Hello @connellyw, here is some feedback on the first two chapters of your senior thesis:

- [x] - Although it is not specific to the chapters, it is important to draw attention to the fact that the implementation of your tool still needs considerable work to meet baseline standards.
- [x] - Overall, the content is poorly formatted and lacking in sufficient detail.
- [x] - I also want to point out that the content inside of your research notebook is not sufficient. During the Spring 2023 semester you need to make sure that you invest time to document the progress that you are making on your project in dated entries.
- [x] - It is hard to read all of the graphs and tables because they are too large and too blurry.
- [x] - The key contributions that your project aims to make are still not yet clear.
- [x] - The thesis itself contains template content that you need to remove so as to personalize the thesis. For instance, please do not include the template content in your abstract.
- [x] - The way in which you highlight the ethical concerns meets the baseline requirements. However, this content needs to be further developed, especially for a project about crypto-currency. For instance, don't you think that it is, in fact, still possible to profit from open source?
- [x] - Did you make the graphs that are inside of your thesis? Or, were they produced elsewhere?
- [x] - There are a number of terms that are not defined that appear in the graphs. Overall, please make sure that the content in your figures and tables is better integrated into the thesis.
- [x] - The second chapter is very short. Can you please extend it significantly? You need to include more of the foundational details about cryptography and how it connects to currencies.
- [x] - There are additional problems in your thesis regarding spelling, formatting, and page layout. Overall, these characteristics of your thesis cast doubt onto the argument you are making.
- [x] - Going forward, please make sure that you regularly commit to your repository and perform more releases of your senior thesis project. It is also important that we meet more regularly during the upcoming Spring 2023 semester. You need to also make sure that you record details about our meetings inside of your research notebook --- it does not seem that you often completed this task.

**Comment by gkapfham** [comment]
Hello @connellyw, please keep me updated as you make progress on resolving these issues. Overall, I would suggest that you work on these tasks during the break. You can also convert my points to a checklist and then indicate which tasks you have completed. Sounds good?

**Comment by connellyw** [comment]
Need to still fix the content formating issue.

**Comment by connellyw** [comment]
fixed formating
