### ISSUE TITLE
Feedback on Chapter Three

### ISSUE THREAD

**Issue by mceccarelli** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-connellyw#9]
Obviously, there are some formatting issues to iron out, both with the pictures and their descriptions.

I appreciate how you unpack all the tools that are required to make your program run.  These aid your feasibility argument, and explain to the reader how they are essential and what their function is from your perspective.

I think going into more detail on exactly how PCA works and what you hope your results will be can be effective for you.  Your chapter will be more robust and understandable with a few additions.

**Comment by connellyw** [comment]
added details and fixed formating
